import { AppDataSource } from '../data-source';
import { ReportAudit } from '../entity/ReportAudit';

/**
 * @description Insert report generation audit record
 * @param {number} userId - The ID of the user generating the report
 * @param {number} assessmentId - The ID of the assessment for the report
 * @returns {Promise<ReportAudit>} - The created report audit record
 */
export const insertReportAuditRecord = (userId: number, assessmentId: number): Promise<ReportAudit> => {
  return new Promise(async (resolve, reject) => {
    try {
      const reportAuditRepository = AppDataSource.getRepository(ReportAudit);
      
      // Create the report audit record
      const reportAudit: ReportAudit = new ReportAudit();
      reportAudit.generatedBy = userId;
      reportAudit.assessmentId = assessmentId;
      reportAudit.generatedDate = new Date();
      
      // Save the report audit record
      const newAudit = await reportAuditRepository.save(reportAudit);
      
      console.info(
        `Report generated by user ID: ${newAudit.generatedBy} for assessment ID: ${newAudit.assessmentId} on ${newAudit.generatedDate}`
      );
      
      resolve(newAudit);
    } catch (err) {
      console.error('Error inserting report audit record:', err);
      reject(err);
    }
  });
};